Removing test file to demo PR
wms910/ages-fpn-demo pull request #1
Opened 2020-02-02 22:31 UTC by wms910

2020-02-10 19:37 UTC, TheBonkSmith commented
Hello?

2020-02-10 19:38 UTC, Error404Danny commented
Hello

2020-03-04 16:24 UTC, ishan115 commented
I would say the game in its current state is fine for getting its message across. During playtesting, I like that the character had its movement set up i.e. motion and jump. The basic landscape was clear (at least in terms of where the player is supposed to go). The texture of the ground and hilly terrain was very good, so that was a great touch. There were some scaling issues I found with the fences. I also couldn't go into the house because of the placement of the colliders.  The terrain eventually became very steep, making it difficult to traverse through. I suggested using the smooth brush to make them a bit more levelled. The final pyramid was very big, so it wasn't possible to go to the top of the pyramid. I suggested instead of making the pyramid smaller, they can increase the jump height of the character. All in all, a solid 7/10.

2020-03-07 01:12 UTC, TheBonkSmith commented
What was your overall impression of the playthrough?
Excellent, good expansive feel, makes me want to adventure and explore what it has to offer.


Was all the geometry / terrain / set pieces textured or have vertex color painting?
Fair, I think there were two untextured things that I noticed but everything else was textured and it fit what it seems he was going for.


Were you able to get some context about the world through the geometry/terrain, textures and set pieces?
Excellent, I was able to get some context, the large pyramid gave a dominating presence that drew me towards it.


Was the space properly lit?
Excellent, I didn’t come across any problems with the lighting.


Did the areas feel spaced out proportionally to the player character?
Fair, The areas were pretty far apart where I did have to take a while to get to them, I think the areas could be closer but still give that distant feel.


Was the playthrough functional? 
Excellent, I had no problems functionality wise while playing.

2020-04-15 00:03 UTC, merged

2020-04-15 01:04 UTC, VinylKnight requested changes
A large portion of the code has been made compact and easily understandable as I went through each commit starting from the second tutorial. I did have a bit of confusion as many of the assets came with their own script as well and created a multitude of extra folders within the project. I would suggest attempting to minimize the number of folders present within the project. The most concerning is the two scene folders that exist within the asset directory. I was unsure of what scene I was supposed to open to access the project. The project follows code conventions pretty accurately with consistent spacing and capitalization with Variables and methods. Variables within the teleport script are public and I believe that it may cause problems later on. The project worked well with minor exceptions when trying the color switches as they kept giving me errors to assign the toggle objects to the toggle set active script. In the end, most of the style conventions for both unity and the scripts were maintained or corrected in subsequent commits. The biggest concerns being the variables within the teleport script being public and the naming of the Check scripts as it was unclear as to its purpose.

2020-04-15 01:04 UTC, VinylKnight commented on Assets/Scripts/DetectLookedAtInteractive.cs
> +///
Remove The extra space if not in use by the code to minimize file size.

2020-04-15 01:04 UTC, VinylKnight commented on Assets/Scripts/InteractWithLookedAt.cs
> +    void Update()
maybe add a space here to more clearly distinguish between DetectLookedAtInteractive and the update function.

2020-04-15 01:04 UTC, VinylKnight commented on Assets/Scripts/Interfaces/IInteractive.cs
> +/// Interface for elements the playeyer can interact with by pressing the Interact button.
Be careful to look back at the code for your project for spelling errors.

2020-04-15 01:04 UTC, VinylKnight commented on Assets/Scripts/ToggleSetActive.cs
> +    private bool isReusable = true;
The space between the serialized field does distinguish the two fields but try not to space out the variables too much as to avoid making a large script file filled with an abundance of spaces in between the code

2020-04-15 01:04 UTC, VinylKnight commented on Assets/Scripts/Teleport.cs
> +
Try to make your variables private so as to avoid having other scripts or editors permanently change the default value. They can be set as a serialized fields that can be changed or manipulated by the editor and other scripts. You can also create private variables that can hold the values being manipulated but can be overridden by the values presented by the game so as to avoid magic numbers or permanent changes to public variables.